
 const mongoose = require('mongoose');

 const daySchema = new mongoose.Schema({
   block1:[mongoose.Schema.Types.Mixed],
   block2:[mongoose.Schema.Types.Mixed],
   block3:[mongoose.Schema.Types.Mixed],
   block4:[mongoose.Schema.Types.Mixed],
   block5:[mongoose.Schema.Types.Mixed],
   block6:[mongoose.Schema.Types.Mixed],
   block7:[mongoose.Schema.Types.Mixed],
   block8:[mongoose.Schema.Types.Mixed],
   block9:[mongoose.Schema.Types.Mixed],
   block10:[mongoose.Schema.Types.Mixed],
   block11:[mongoose.Schema.Types.Mixed],
   block12:[mongoose.Schema.Types.Mixed],
   block13:[mongoose.Schema.Types.Mixed],
   block14:[mongoose.Schema.Types.Mixed],
   block15:[mongoose.Schema.Types.Mixed],
   block16:[mongoose.Schema.Types.Mixed],
   block17:[mongoose.Schema.Types.Mixed],
   block18:[mongoose.Schema.Types.Mixed],
   block19:[mongoose.Schema.Types.Mixed],
   block20:[mongoose.Schema.Types.Mixed],
   block21:[mongoose.Schema.Types.Mixed],
   block22:[mongoose.Schema.Types.Mixed],
   block23:[mongoose.Schema.Types.Mixed],
   block24:[mongoose.Schema.Types.Mixed],
   block25:[mongoose.Schema.Types.Mixed],
   block26:[mongoose.Schema.Types.Mixed],
   block27:[mongoose.Schema.Types.Mixed],
   block28:[mongoose.Schema.Types.Mixed],
   block29:[mongoose.Schema.Types.Mixed],
   block30:[mongoose.Schema.Types.Mixed],
   block31:[mongoose.Schema.Types.Mixed],
   block32:[mongoose.Schema.Types.Mixed],
   block33:[mongoose.Schema.Types.Mixed],
   block34:[mongoose.Schema.Types.Mixed],
   block35:[mongoose.Schema.Types.Mixed],
   block36:[mongoose.Schema.Types.Mixed],
   block37:[mongoose.Schema.Types.Mixed],
   block38:[mongoose.Schema.Types.Mixed],
   block39:[mongoose.Schema.Types.Mixed],
   block40:[mongoose.Schema.Types.Mixed],
   block41:[mongoose.Schema.Types.Mixed],
   block42:[mongoose.Schema.Types.Mixed],
   block43:[mongoose.Schema.Types.Mixed],
   block44:[mongoose.Schema.Types.Mixed],
   block45:[mongoose.Schema.Types.Mixed],
   block46:[mongoose.Schema.Types.Mixed],
   block47:[mongoose.Schema.Types.Mixed],
   block48:[mongoose.Schema.Types.Mixed],
   block49:[mongoose.Schema.Types.Mixed],
   block50:[mongoose.Schema.Types.Mixed],
   block51:[mongoose.Schema.Types.Mixed],
   block52:[mongoose.Schema.Types.Mixed],
   block53:[mongoose.Schema.Types.Mixed],
   block54:[mongoose.Schema.Types.Mixed],
   block55:[mongoose.Schema.Types.Mixed],
   block56:[mongoose.Schema.Types.Mixed],
   block57:[mongoose.Schema.Types.Mixed],
   block58:[mongoose.Schema.Types.Mixed],
   block59:[mongoose.Schema.Types.Mixed],
   block60:[mongoose.Schema.Types.Mixed],
   block61:[mongoose.Schema.Types.Mixed],
   block62:[mongoose.Schema.Types.Mixed],
   block63:[mongoose.Schema.Types.Mixed],
   block64:[mongoose.Schema.Types.Mixed],
   block65:[mongoose.Schema.Types.Mixed],
   block66:[mongoose.Schema.Types.Mixed],
   block67:[mongoose.Schema.Types.Mixed],
   block68:[mongoose.Schema.Types.Mixed],
   block69:[mongoose.Schema.Types.Mixed],
   block70:[mongoose.Schema.Types.Mixed],
   block71:[mongoose.Schema.Types.Mixed],
   block72:[mongoose.Schema.Types.Mixed],
   block73:[mongoose.Schema.Types.Mixed],
   block74:[mongoose.Schema.Types.Mixed],
   block75:[mongoose.Schema.Types.Mixed],
   block76:[mongoose.Schema.Types.Mixed],
   block77:[mongoose.Schema.Types.Mixed],
   block78:[mongoose.Schema.Types.Mixed],
   block79:[mongoose.Schema.Types.Mixed],
   block80:[mongoose.Schema.Types.Mixed],
   block81:[mongoose.Schema.Types.Mixed],
   block82:[mongoose.Schema.Types.Mixed],
   block83:[mongoose.Schema.Types.Mixed],
   block84:[mongoose.Schema.Types.Mixed],
   block85:[mongoose.Schema.Types.Mixed],
   block86:[mongoose.Schema.Types.Mixed],
   block87:[mongoose.Schema.Types.Mixed],
   block88:[mongoose.Schema.Types.Mixed],
   block89:[mongoose.Schema.Types.Mixed],
   block90:[mongoose.Schema.Types.Mixed],
   block91:[mongoose.Schema.Types.Mixed],
   block92:[mongoose.Schema.Types.Mixed],
   block93:[mongoose.Schema.Types.Mixed],
   block94:[mongoose.Schema.Types.Mixed],
   block95:[mongoose.Schema.Types.Mixed],
   block96:[mongoose.Schema.Types.Mixed],
 })

const DayModel = mongoose.model('DayModel',daySchema);

module.exports= DayModel;
 ////////////////this will be our pseudo route
//since we dont have a router.post we need each day in 3 weeks to already have an id
